### ISSUE TITLE
Empty .pkgdef file

### ISSUE THREAD

**Issue by Stroichik** [madskristensen/ThemeConverter#3]
I follow video instructions. But when i add .jsonc file it already appears with empty .pkgdef file. When i try to convert .jsonc file .pkgdef file stays empty. If i remove .pkgdef file and try converting again, no new .pkgdef file appears.

**Comment by Stroichik** [comment]
A new empty .pkgdef file appears if i use "Custom tool" command on .jsonc file.

**Comment by AndreMenew** [comment]
If I rename the .jsonc file, it automatically creates an empty .pkgdef file.

**Comment by SamYuan** [comment]
Like you, I'm confused that I don't see any possible error messages

**Comment by SamYuan** [comment]
The problem is solved. Look here
https://github.com/microsoft/theme-converter-for-vs

**Comment by wangxa** [comment]
According to my experience, there are two possibilities:

1. The `.jsonc` is not a valid standard JSON format. Usually, the `.jsonc` contains `//` comments. In the standard JSON, `//` is not allowed. You need to remove all the `//`.
2. This tool will call `ThemeConverter.exe`, which requires `.NET 5.0 runtime`. If you have not installed this requirement, the `ThemeConverter.exe` will not work, and the generated `.pkgdef` file is empty. 

I think the author should add these two points as notes.

**Comment by madskristensen** [comment]
Good point on the .NET 5 requirement. The comments are being stripped before the call is made to the ThemeConverter.exe

**Comment by Abhishek32971** [comment]
> The problem is solved. Look here https://github.com/microsoft/theme-converter-for-vs

thankyou

**Comment by Stroichik** [comment]
The problem is solved. Look here https://github.com/microsoft/theme-converter-for-vs
